deploy: Workaround pep517 error.
Was seeing:

```
$ /opt/shaman/bin/pip2 install -U --force-reinstall -e git+https://github.com/ceph/shaman@master#egg=shaman
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining shaman from git+https://github.com/ceph/shaman@master#egg=shaman
  Updating /opt/shaman/src/shaman clone (to revision master)
  Running command git fetch -q --tags
  Running command git reset --hard -q 312f501e2491cb209beb735f15c523ddc4c7a33e
Processing /home/ubuntu/.cache/pip/wheels/b6/87/95/8f5cde3038191d06c70f795e07b8887ad12d09801689a75292/pecan-1.3.3-cp27-none-any.whl
Collecting sqlalchemy
  Using cached SQLAlchemy-1.3.15.tar.gz (6.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/opt/shaman/local/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
BackendUnavailable
```

Signed-off-by: David Galloway <dgallowa@redhat.com>